#!/usr/bin/env bash
# finds all directories of $1 or . then gets the sizes of each directory
dir=${1:-.}

find $dir -maxdepth 1 -type d -exec du -s {} \; | awk '
    function human(x) {
        if (x<1000) {return x} else {x/=1024}
        s="kMGTEPZY";
        while (x>=1000 && length(s)>1)
            {x/=1024; s=substr(s,2)}
        return int(x+0.5) substr(s,1,1)
    }
    {sub(/^[0-9]+/, human($1)); print}'


