#!/usr/bin/python
import sys
import datetime

template = """# {date}

## Morning checklist

* [ ] First thing stretch
* [ ] Early water theraphy
* [ ] Lumosity brain game
* [ ] Morning heliocare
* [ ] Exercise
* [ ] Shower
* [ ] Coffee
* [ ] Breakfast (Smoothie?)
* [ ] Time in

## Lunch habits

* [ ] Eat fruits first
* [ ] Dont overeat
* [ ] Post lunch isotret
* [ ] Post lunch collagen

## Evening checklist

* [ ] WC Journal
* [ ] Time out
* [ ] Night collagen
* [ ] Goals review

## Dinner habits

* [ ] Eat fruits first
* [ ] Dont overeat
* [ ] Post dinner brain meds

## Targeted wins

* [ ]
* [ ]
* [ ]

## Losses

## Logs

## Notes

## Todo tomorrow

* [ ]
* [ ]
* [ ]

"""

date = datetime.date.today()
print(template.format(date=date))
